# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\BorrarEvento.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoBorrarEvento(object):
    def setupUi(self, DialogoBorrarEvento):
        DialogoBorrarEvento.setObjectName("DialogoBorrarEvento")
        DialogoBorrarEvento.resize(750, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogoBorrarEvento)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_Titulo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Titulo.setObjectName("horizontalLayout_Titulo")
        self.BackButton_DeleteEvent = QtWidgets.QToolButton(DialogoBorrarEvento)
        self.BackButton_DeleteEvent.setAutoRaise(True)
        self.BackButton_DeleteEvent.setObjectName("BackButton_DeleteEvent")
        self.horizontalLayout_Titulo.addWidget(self.BackButton_DeleteEvent)
        self.TitleLabel_DeleteEvent = QtWidgets.QLabel(DialogoBorrarEvento)
        self.TitleLabel_DeleteEvent.setObjectName("TitleLabel_DeleteEvent")
        self.horizontalLayout_Titulo.addWidget(self.TitleLabel_DeleteEvent)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Titulo.addItem(spacerItem)
        self.horizontalLayout_Titulo.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_Titulo)
        self.EventList_Table_Delete = QtWidgets.QTableWidget(DialogoBorrarEvento)
        self.EventList_Table_Delete.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.EventList_Table_Delete.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.EventList_Table_Delete.setShowGrid(False)
        self.EventList_Table_Delete.setObjectName("EventList_Table_Delete")
        self.EventList_Table_Delete.setColumnCount(4)
        self.EventList_Table_Delete.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.EventList_Table_Delete.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventList_Table_Delete.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventList_Table_Delete.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventList_Table_Delete.setHorizontalHeaderItem(3, item)
        self.EventList_Table_Delete.horizontalHeader().setVisible(True)
        self.EventList_Table_Delete.horizontalHeader().setHighlightSections(False)
        self.EventList_Table_Delete.horizontalHeader().setStretchLastSection(True)
        self.EventList_Table_Delete.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.EventList_Table_Delete)
        self.horizontalLayout_Boton = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Boton.setObjectName("horizontalLayout_Boton")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Boton.addItem(spacerItem1)
        self.ConfirmDelete_Btn = QtWidgets.QPushButton(DialogoBorrarEvento)
        self.ConfirmDelete_Btn.setMinimumSize(QtCore.QSize(120, 45))
        self.ConfirmDelete_Btn.setObjectName("ConfirmDelete_Btn")
        self.horizontalLayout_Boton.addWidget(self.ConfirmDelete_Btn)
        self.verticalLayout.addLayout(self.horizontalLayout_Boton)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(DialogoBorrarEvento)
        QtCore.QMetaObject.connectSlotsByName(DialogoBorrarEvento)

    def retranslateUi(self, DialogoBorrarEvento):
        _translate = QtCore.QCoreApplication.translate
        DialogoBorrarEvento.setWindowTitle(_translate("DialogoBorrarEvento", "Borrar Evento"))
        DialogoBorrarEvento.setStyleSheet(_translate("DialogoBorrarEvento", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* --- Título Principal --- */\n"
"QLabel[objectName=\"TitleLabel_DeleteEvent\"] {\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    padding-bottom: 10px;\n"
"    background-color: transparent;\n"
"    indent: 0; /* Reseteamos el indent original */\n"
"}\n"
"\n"
"/* --- Botón de Atrás --- */\n"
"QToolButton {\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #555555;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding-right: 10px;\n"
"}\n"
"QToolButton:hover {\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* --- Botón de \"Peligro\" (Borrar) --- */\n"
"QPushButton[objectName=\"ConfirmDelete_Btn\"] {\n"
"    background-color: #FFEBEE; /* Rosa pastel */\n"
"    color: #D32F2F; /* Rojo oscuro */\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px 18px;\n"
"    min-height: 28px; /* min-height de 45px del original */\n"
"}\n"
"QPushButton[objectName=\"ConfirmDelete_Btn\"]:hover {\n"
"    background-color: #FFCDD2;\n"
"}\n"
"QPushButton[objectName=\"ConfirmDelete_Btn\"]:pressed {\n"
"    background-color: #EF9A9A;\n"
"}\n"
"\n"
"/* --- Tablas --- */\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E0E0E0;\n"
"    gridline-color: #E0E0E0; /* Color de la cuadrícula */\n"
"    border-radius: 8px; /* ESQUINAS REDONDEADAS */\n"
"    font-size: 10pt; /* Fuente original */\n"
"}\n"
"\n"
"/* --- Cabeceras de Tablas --- */\n"
"QHeaderView::section {\n"
"    background-color: #F1F3F5; /* Un gris muy claro para cabeceras */\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"}\n"
"   "))
        self.BackButton_DeleteEvent.setText(_translate("DialogoBorrarEvento", "<"))
        self.TitleLabel_DeleteEvent.setText(_translate("DialogoBorrarEvento", "Borrar evento"))
        self.EventList_Table_Delete.setSortingEnabled(True)
        item = self.EventList_Table_Delete.horizontalHeaderItem(0)
        item.setText(_translate("DialogoBorrarEvento", "Nombre"))
        item = self.EventList_Table_Delete.horizontalHeaderItem(1)
        item.setText(_translate("DialogoBorrarEvento", "Fecha"))
        item = self.EventList_Table_Delete.horizontalHeaderItem(2)
        item.setText(_translate("DialogoBorrarEvento", "Ubicacion"))
        item = self.EventList_Table_Delete.horizontalHeaderItem(3)
        item.setText(_translate("DialogoBorrarEvento", "Organizador"))
        self.ConfirmDelete_Btn.setText(_translate("DialogoBorrarEvento", "Borrar"))
