# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\CrudEvento.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# ****** MODIFICADO MANUALMENTE PARA USAR QWidget EN LUGAR DE QMainWindow ******


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    # Cambiamos 'MainWindow' por 'Form' para que acepte un QWidget
    def setupUi(self, Form):
        Form.setObjectName("Form") # 'Form' en lugar de 'MainWindow'
        Form.resize(904, 617)
        
        # ELIMINAMOS self.centralwidget. El layout principal va directo en el Form.
        self.verticalLayout = QtWidgets.QVBoxLayout(Form) # 'Form' es el padre
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # Cambiamos el padre de 'self.centralwidget' a 'Form'
        self.label = QtWidgets.QLabel(Form) 
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        
        # Cambiamos el padre de 'self.centralwidget' a 'Form'
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        # Cambiamos el padre de 'self.centralwidget' a 'Form'
        self.tblEventos = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tblEventos.setFont(font)
        self.tblEventos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblEventos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblEventos.setShowGrid(False)
        self.tblEventos.setObjectName("tblEventos")
        self.tblEventos.setColumnCount(4)
        self.tblEventos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblEventos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEventos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEventos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEventos.setHorizontalHeaderItem(3, item)
        self.tblEventos.horizontalHeader().setVisible(True)
        self.tblEventos.horizontalHeader().setHighlightSections(False)
        self.tblEventos.horizontalHeader().setStretchLastSection(True)
        self.tblEventos.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tblEventos)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        
        self.verticalLayout_Botones = QtWidgets.QVBoxLayout()
        self.verticalLayout_Botones.setObjectName("verticalLayout_Botones")
        self.horizontalLayout_Botones1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Botones1.setObjectName("horizontalLayout_Botones1")
        
        # Cambiamos el padre de 'self.centralwidget' a 'Form'
        self.btnAsignarMesas = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAsignarMesas.sizePolicy().hasHeightForWidth())
        self.btnAsignarMesas.setSizePolicy(sizePolicy)
        self.btnAsignarMesas.setObjectName("btnAsignarMesas")
        self.horizontalLayout_Botones1.addWidget(self.btnAsignarMesas)
        
        # Cambiamos el padre de 'self.centralwidget' a 'Form'
        self.btnCrearEvento = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCrearEvento.sizePolicy().hasHeightForWidth())
        self.btnCrearEvento.setSizePolicy(sizePolicy)
        self.btnCrearEvento.setObjectName("btnCrearEvento")
        self.horizontalLayout_Botones1.addWidget(self.btnCrearEvento)
        
        # Cambiamos el padre de 'self.centralwidget' a 'Form'
        self.btnActualizarEvento = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnActualizarEvento.sizePolicy().hasHeightForWidth())
        self.btnActualizarEvento.setSizePolicy(sizePolicy)
        self.btnActualizarEvento.setObjectName("btnActualizarEvento")
        self.horizontalLayout_Botones1.addWidget(self.btnActualizarEvento)
        
        self.verticalLayout_Botones.addLayout(self.horizontalLayout_Botones1)
        self.horizontalLayout_Botones2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Botones2.setObjectName("horizontalLayout_Botones2")
        
        # Cambiamos el padre de 'self.centralwidget' a 'Form'
        self.btnBorrarEvento = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBorrarEvento.sizePolicy().hasHeightForWidth())
        self.btnBorrarEvento.setSizePolicy(sizePolicy)
        self.btnBorrarEvento.setObjectName("btnBorrarEvento")
        self.horizontalLayout_Botones2.addWidget(self.btnBorrarEvento)
        
        # Cambiamos el padre de 'self.centralwidget' a 'Form'
        self.btnGenerarCSV = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenerarCSV.sizePolicy().hasHeightForWidth())
        self.btnGenerarCSV.setSizePolicy(sizePolicy)
        self.btnGenerarCSV.setObjectName("btnGenerarCSV")
        self.horizontalLayout_Botones2.addWidget(self.btnGenerarCSV)
        
        self.verticalLayout_Botones.addLayout(self.horizontalLayout_Botones2)
        self.verticalLayout.addLayout(self.verticalLayout_Botones)
        self.verticalLayout.setStretch(1, 10)
        
        # --- ELIMINAMOS LAS LÍNEAS DE QMainWindow ---
        # ELIMINADO: MainWindow.setCentralWidget(self.centralwidget)
        # ELIMINADO: self.menubar = ...
        # ELIMINADO: MainWindow.setMenuBar(self.menubar)
        # ELIMINADO: self.statusbar = ...
        # ELIMINADO: MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Form) # 'Form' en lugar de 'MainWindow'
        QtCore.QMetaObject.connectSlotsByName(Form) # 'Form' en lugar de 'MainWindow'

    # Cambiamos 'MainWindow' por 'Form'
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        # 'Form' en lugar de 'MainWindow'
        Form.setWindowTitle(_translate("Form", "Gestor de Eventos")) 
        self.label.setText(_translate("Form", "Gestor de Eventos"))
        self.pushButton.setText(_translate("Form", "Abrir Ruta de CSV"))
        self.tblEventos.setSortingEnabled(True)
        item = self.tblEventos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nombre"))
        item = self.tblEventos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Fecha"))
        item = self.tblEventos.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Ubicacion"))
        item = self.tblEventos.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Organizador"))
        self.btnAsignarMesas.setText(_translate("Form", "Asignar mesas"))
        self.btnCrearEvento.setText(_translate("Form", "Crear evento"))
        self.btnActualizarEvento.setText(_translate("Form", "Actualizar evento"))
        self.btnBorrarEvento.setText(_translate("Form", "Borrar evento"))
        self.btnGenerarCSV.setText(_translate("Form", "Generar CSV"))