# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\CrearEvento1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(934, 525)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_Titulo_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Titulo_3.setObjectName("horizontalLayout_Titulo_3")
        self.BackButton_CreateEvent = QtWidgets.QToolButton(Form)
        self.BackButton_CreateEvent.setAutoRaise(True)
        self.BackButton_CreateEvent.setObjectName("BackButton_CreateEvent")
        self.horizontalLayout_Titulo_3.addWidget(self.BackButton_CreateEvent)
        self.TitleLabel_CreateEvent = QtWidgets.QLabel(Form)
        self.TitleLabel_CreateEvent.setObjectName("TitleLabel_CreateEvent")
        self.horizontalLayout_Titulo_3.addWidget(self.TitleLabel_CreateEvent)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Titulo_3.addItem(spacerItem)
        self.horizontalLayout_Titulo_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_Titulo_3)
        self.gridLayout_Content_3 = QtWidgets.QGridLayout()
        self.gridLayout_Content_3.setObjectName("gridLayout_Content_3")
        self.Label_EventName = QtWidgets.QLabel(Form)
        self.Label_EventName.setObjectName("Label_EventName")
        self.gridLayout_Content_3.addWidget(self.Label_EventName, 0, 0, 1, 1)
        self.Input_EventName = QtWidgets.QLineEdit(Form)
        self.Input_EventName.setObjectName("Input_EventName")
        self.gridLayout_Content_3.addWidget(self.Input_EventName, 0, 1, 1, 1)
        self.Label_NumTables = QtWidgets.QLabel(Form)
        self.Label_NumTables.setObjectName("Label_NumTables")
        self.gridLayout_Content_3.addWidget(self.Label_NumTables, 0, 2, 1, 1)
        self.Input_NumTables = QtWidgets.QSpinBox(Form)
        self.Input_NumTables.setMinimum(1)
        self.Input_NumTables.setObjectName("Input_NumTables")
        self.gridLayout_Content_3.addWidget(self.Input_NumTables, 0, 3, 1, 1)
        self.Label_EventDate = QtWidgets.QLabel(Form)
        self.Label_EventDate.setObjectName("Label_EventDate")
        self.gridLayout_Content_3.addWidget(self.Label_EventDate, 1, 0, 1, 1)
        self.Input_EventDate = QtWidgets.QLineEdit(Form)
        self.Input_EventDate.setObjectName("Input_EventDate")
        self.gridLayout_Content_3.addWidget(self.Input_EventDate, 1, 1, 1, 1)
        self.UploadCSV_Btn = QtWidgets.QPushButton(Form)
        self.UploadCSV_Btn.setObjectName("UploadCSV_Btn")
        self.gridLayout_Content_3.addWidget(self.UploadCSV_Btn, 1, 2, 1, 2)
        self.Label_EventLocation = QtWidgets.QLabel(Form)
        self.Label_EventLocation.setObjectName("Label_EventLocation")
        self.gridLayout_Content_3.addWidget(self.Label_EventLocation, 2, 0, 1, 1)
        self.Input_EventLocation = QtWidgets.QLineEdit(Form)
        self.Input_EventLocation.setObjectName("Input_EventLocation")
        self.gridLayout_Content_3.addWidget(self.Input_EventLocation, 2, 1, 1, 1)
        self.CreateManual_Btn = QtWidgets.QPushButton(Form)
        self.CreateManual_Btn.setObjectName("CreateManual_Btn")
        self.gridLayout_Content_3.addWidget(self.CreateManual_Btn, 2, 2, 1, 2)
        self.Label_EventOrganizer = QtWidgets.QLabel(Form)
        self.Label_EventOrganizer.setObjectName("Label_EventOrganizer")
        self.gridLayout_Content_3.addWidget(self.Label_EventOrganizer, 3, 0, 1, 1)
        self.Input_EventOrganizer = QtWidgets.QLineEdit(Form)
        self.Input_EventOrganizer.setObjectName("Input_EventOrganizer")
        self.gridLayout_Content_3.addWidget(self.Input_EventOrganizer, 3, 1, 1, 1)
        self.gridLayout_Content_3.setColumnStretch(1, 2)
        self.gridLayout_Content_3.setColumnStretch(3, 1)
        self.verticalLayout.addLayout(self.gridLayout_Content_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 269, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.FinishCreateEvent_Btn = QtWidgets.QPushButton(Form)
        self.FinishCreateEvent_Btn.setMinimumSize(QtCore.QSize(0, 45))
        self.FinishCreateEvent_Btn.setObjectName("FinishCreateEvent_Btn")
        self.verticalLayout.addWidget(self.FinishCreateEvent_Btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Crear Evento"))
        Form.setStyleSheet(_translate("Form", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333;\n"
"    font-size: 10pt; /* Fuente base para etiquetas */\n"
"}\n"
"\n"
"/* --- Título Principal --- */\n"
"QLabel[objectName=\"TitleLabel_CreateEvent\"] {\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    padding-bottom: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* --- Botón de Atrás --- */\n"
"QToolButton {\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #555555;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding-right: 10px;\n"
"}\n"
"QToolButton:hover {\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* --- Botones Principales --- */\n"
"QPushButton {\n"
"    background-color: #E0EFFF; /* Azul pastel */\n"
"    color: #2C3E50;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px 18px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C6DFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B0D0FF;\n"
"}\n"
"\n"
"/* --- Botón de Finalizar (más grande) --- */\n"
"QPushButton[objectName=\"FinishCreateEvent_Btn\"] {\n"
"    font-size: 14pt; /* Más grande como en el original */\n"
"    padding: 15px;\n"
"}\n"
"\n"
"/* --- Campos de Texto y SpinBox --- */\n"
"QLineEdit, QSpinBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #CED4DA; /* Borde gris claro */\n"
"    border-radius: 5px; /* Esquinas redondeadas leves */\n"
"    padding: 8px;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QLineEdit:focus, QSpinBox:focus {\n"
"    border: 1px solid #80bdff; /* Borde azul al seleccionar */\n"
"}\n"
"   "))
        self.BackButton_CreateEvent.setText(_translate("Form", "<"))
        self.TitleLabel_CreateEvent.setText(_translate("Form", "Crear Evento"))
        self.Label_EventName.setText(_translate("Form", "Nombre"))
        self.Input_EventName.setPlaceholderText(_translate("Form", "Nombre del evento"))
        self.Label_NumTables.setText(_translate("Form", "Numero de mesas"))
        self.Label_EventDate.setText(_translate("Form", "Fecha"))
        self.Input_EventDate.setPlaceholderText(_translate("Form", "dd/mm/yyyy"))
        self.UploadCSV_Btn.setText(_translate("Form", "+ Subir Participantes (CSV)"))
        self.Label_EventLocation.setText(_translate("Form", "Ubicacion"))
        self.Input_EventLocation.setPlaceholderText(_translate("Form", "Lugar de la celebración"))
        self.CreateManual_Btn.setText(_translate("Form", "Crear participantes manualmente"))
        self.Label_EventOrganizer.setText(_translate("Form", "Organizador"))
        self.Input_EventOrganizer.setPlaceholderText(_translate("Form", "Nombre del responsable"))
        self.FinishCreateEvent_Btn.setText(_translate("Form", "Finalizar"))
