# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\AsignarMesas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(703, 542)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_Titulo_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Titulo_3.setObjectName("horizontalLayout_Titulo_3")
        self.BackButton_AssignMenu = QtWidgets.QToolButton(Form)
        self.BackButton_AssignMenu.setAutoRaise(True)
        self.BackButton_AssignMenu.setObjectName("BackButton_AssignMenu")
        self.horizontalLayout_Titulo_3.addWidget(self.BackButton_AssignMenu)
        self.TitleLabel_AssignMenu = QtWidgets.QLabel(Form)
        self.TitleLabel_AssignMenu.setObjectName("TitleLabel_AssignMenu")
        self.horizontalLayout_Titulo_3.addWidget(self.TitleLabel_AssignMenu)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Titulo_3.addItem(spacerItem)
        self.horizontalLayout_Titulo_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_Titulo_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AutoAssign_Btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AutoAssign_Btn.sizePolicy().hasHeightForWidth())
        self.AutoAssign_Btn.setSizePolicy(sizePolicy)
        self.AutoAssign_Btn.setObjectName("AutoAssign_Btn")
        self.verticalLayout.addWidget(self.AutoAssign_Btn)
        self.ManualAssign_Btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManualAssign_Btn.sizePolicy().hasHeightForWidth())
        self.ManualAssign_Btn.setSizePolicy(sizePolicy)
        self.ManualAssign_Btn.setObjectName("ManualAssign_Btn")
        self.verticalLayout.addWidget(self.ManualAssign_Btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Asignar Mesas"))
        Form.setStyleSheet(_translate("Form", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* --- Título Principal --- */\n"
"QLabel[objectName=\"TitleLabel_AssignMenu\"] {\n"
"    font-size: 24pt; /* Unificado con el resto */\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    padding-bottom: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* --- Botón de Atrás --- */\n"
"QToolButton {\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #555555;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding-right: 10px;\n"
"}\n"
"QToolButton:hover {\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* --- Botones Principales (Automático/Manual) --- */\n"
"QPushButton {\n"
"    background-color: #E0EFFF; /* Azul pastel */\n"
"    color: #2C3E50;\n"
"    font-size: 20pt; /* Tamaño de fuente grande del original */\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px 18px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #C6DFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B0D0FF;\n"
"}\n"
"   "))
        self.BackButton_AssignMenu.setText(_translate("Form", "<"))
        self.TitleLabel_AssignMenu.setText(_translate("Form", "Asignar Mesas"))
        self.AutoAssign_Btn.setText(_translate("Form", "Automatico"))
        self.ManualAssign_Btn.setText(_translate("Form", "Manual"))
