# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\AsignarMesas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1177, 652)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_Titulo_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Titulo_3.setObjectName("horizontalLayout_Titulo_3")
        self.btnAtras_asignarmesas = QtWidgets.QToolButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnAtras_asignarmesas.setFont(font)
        self.btnAtras_asignarmesas.setAutoRaise(True)
        self.btnAtras_asignarmesas.setObjectName("btnAtras_asignarmesas")
        self.horizontalLayout_Titulo_3.addWidget(self.btnAtras_asignarmesas)
        self.labelTitulo_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo_3.setFont(font)
        self.labelTitulo_3.setObjectName("labelTitulo_3")
        self.horizontalLayout_Titulo_3.addWidget(self.labelTitulo_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Titulo_3.addItem(spacerItem)
        self.horizontalLayout_Titulo_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_Titulo_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_Automatico = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Automatico.sizePolicy().hasHeightForWidth())
        self.btn_Automatico.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_Automatico.setFont(font)
        self.btn_Automatico.setObjectName("btn_Automatico")
        self.verticalLayout.addWidget(self.btn_Automatico)
        self.btn_Manual = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Manual.sizePolicy().hasHeightForWidth())
        self.btn_Manual.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_Manual.setFont(font)
        self.btn_Manual.setObjectName("btn_Manual")
        self.verticalLayout.addWidget(self.btn_Manual)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnAtras_asignarmesas.setText(_translate("Form", "<"))
        self.labelTitulo_3.setText(_translate("Form", "Asignar Mesas"))
        self.btn_Automatico.setText(_translate("Form", "Automatico"))
        self.btn_Manual.setText(_translate("Form", "Manual"))
