# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\AsignarMesasAutomatico.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(667, 381)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_Titulo_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Titulo_3.setObjectName("horizontalLayout_Titulo_3")
        self.BackButton_AutoAssign = QtWidgets.QToolButton(Form)
        self.BackButton_AutoAssign.setAutoRaise(True)
        self.BackButton_AutoAssign.setObjectName("BackButton_AutoAssign")
        self.horizontalLayout_Titulo_3.addWidget(self.BackButton_AutoAssign)
        self.TitleLabel_AutoAssign = QtWidgets.QLabel(Form)
        self.TitleLabel_AutoAssign.setObjectName("TitleLabel_AutoAssign")
        self.horizontalLayout_Titulo_3.addWidget(self.TitleLabel_AutoAssign)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Titulo_3.addItem(spacerItem)
        self.horizontalLayout_Titulo_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_Titulo_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Results_Table = QtWidgets.QTableWidget(Form)
        self.Results_Table.setRowCount(0)
        self.Results_Table.setColumnCount(2)
        self.Results_Table.setObjectName("Results_Table")
        item = QtWidgets.QTableWidgetItem()
        self.Results_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Results_Table.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.Results_Table)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ViewExceptions_Btn = QtWidgets.QPushButton(Form)
        self.ViewExceptions_Btn.setObjectName("ViewExceptions_Btn")
        self.verticalLayout.addWidget(self.ViewExceptions_Btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Asignación Automática"))
        Form.setStyleSheet(_translate("Form", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* --- Título Principal --- */\n"
"QLabel[objectName=\"TitleLabel_AutoAssign\"] {\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    padding-bottom: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* --- Botón de Atrás --- */\n"
"QToolButton {\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #555555;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding-right: 10px;\n"
"}\n"
"QToolButton:hover {\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* --- Botones Principales --- */\n"
"QPushButton {\n"
"    background-color: #E0EFFF; /* Azul pastel */\n"
"    color: #2C3E50;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px 18px;\n"
"    min-height: 28px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #C6DFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B0D0FF;\n"
"}\n"
"\n"
"/* --- Tablas --- */\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E0E0E0;\n"
"    gridline-color: #E0E0E0; /* Color de la cuadrícula */\n"
"    border-radius: 8px; /* ESQUINAS REDONDEADAS */\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"/* --- Cabeceras de Tablas --- */\n"
"QHeaderView::section {\n"
"    background-color: #F1F3F5; /* Un gris muy claro para cabeceras */\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"}\n"
"   "))
        self.BackButton_AutoAssign.setText(_translate("Form", "<"))
        self.TitleLabel_AutoAssign.setText(_translate("Form", "Asignar Mesas Automatico"))
        item = self.Results_Table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mesa"))
        item = self.Results_Table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Participantes"))
        self.ViewExceptions_Btn.setText(_translate("Form", "Ver Excepciones"))
