# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\AsignarMesasExcepciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(996, 668)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_Titulo_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Titulo_3.setObjectName("horizontalLayout_Titulo_3")
        self.BackButton_Exceptions = QtWidgets.QToolButton(Form)
        self.BackButton_Exceptions.setAutoRaise(True)
        self.BackButton_Exceptions.setObjectName("BackButton_Exceptions")
        self.horizontalLayout_Titulo_3.addWidget(self.BackButton_Exceptions)
        self.TitleLabel_Exceptions = QtWidgets.QLabel(Form)
        self.TitleLabel_Exceptions.setObjectName("TitleLabel_Exceptions")
        self.horizontalLayout_Titulo_3.addWidget(self.TitleLabel_Exceptions)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Titulo_3.addItem(spacerItem)
        self.horizontalLayout_Titulo_3.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_Titulo_3)
        self.horizontalLayout_Lists = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Lists.setObjectName("horizontalLayout_Lists")
        self.verticalLayout_TableList = QtWidgets.QVBoxLayout()
        self.verticalLayout_TableList.setObjectName("verticalLayout_TableList")
        self.Label_TableParticipants = QtWidgets.QLabel(Form)
        self.Label_TableParticipants.setObjectName("Label_TableParticipants")
        self.verticalLayout_TableList.addWidget(self.Label_TableParticipants)
        self.List_TableParticipants = QtWidgets.QListWidget(Form)
        self.List_TableParticipants.setObjectName("List_TableParticipants")
        self.verticalLayout_TableList.addWidget(self.List_TableParticipants)
        self.horizontalLayout_Lists.addLayout(self.verticalLayout_TableList)
        self.verticalLayout_ExceptionList = QtWidgets.QVBoxLayout()
        self.verticalLayout_ExceptionList.setObjectName("verticalLayout_ExceptionList")
        self.Label_Exceptions = QtWidgets.QLabel(Form)
        self.Label_Exceptions.setObjectName("Label_Exceptions")
        self.verticalLayout_ExceptionList.addWidget(self.Label_Exceptions)
        self.List_Exceptions = QtWidgets.QListWidget(Form)
        self.List_Exceptions.setObjectName("List_Exceptions")
        self.verticalLayout_ExceptionList.addWidget(self.List_Exceptions)
        self.horizontalLayout_Lists.addLayout(self.verticalLayout_ExceptionList)
        self.horizontalLayout_Lists.setStretch(0, 1)
        self.horizontalLayout_Lists.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_Lists)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PrevTable_Btn = QtWidgets.QPushButton(Form)
        self.PrevTable_Btn.setObjectName("PrevTable_Btn")
        self.verticalLayout_2.addWidget(self.PrevTable_Btn)
        self.AddParticipant_Btn = QtWidgets.QPushButton(Form)
        self.AddParticipant_Btn.setObjectName("AddParticipant_Btn")
        self.verticalLayout_2.addWidget(self.AddParticipant_Btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.NextTable_Btn = QtWidgets.QPushButton(Form)
        self.NextTable_Btn.setObjectName("NextTable_Btn")
        self.verticalLayout_4.addWidget(self.NextTable_Btn)
        self.RemoveParticipant_Btn = QtWidgets.QPushButton(Form)
        self.RemoveParticipant_Btn.setObjectName("RemoveParticipant_Btn")
        self.verticalLayout_4.addWidget(self.RemoveParticipant_Btn)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_5.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Resolver Excepciones"))
        Form.setStyleSheet(_translate("Form", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* --- Título Principal --- */\n"
"QLabel[objectName=\"TitleLabel_Exceptions\"] {\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    padding-bottom: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* --- Etiquetas de listas --- */\n"
"QLabel[objectName^=\"Label_\"] {\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    background-color: transparent;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"/* --- Botón de Atrás --- */\n"
"QToolButton {\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #555555;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding-right: 10px;\n"
"}\n"
"QToolButton:hover {\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* --- Botones Principales --- */\n"
"QPushButton {\n"
"    background-color: #E0EFFF; /* Azul pastel */\n"
"    color: #2C3E50;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px;\n"
"    min-height: 28px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #C6DFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B0D0FF;\n"
"}\n"
"\n"
"/* --- Botón de \"Peligro\" (Eliminar) --- */\n"
"QPushButton[objectName=\"RemoveParticipant_Btn\"] {\n"
"    background-color: #FFEBEE; /* Rosa pastel */\n"
"    color: #D32F2F; /* Rojo oscuro */\n"
"}\n"
"QPushButton[objectName=\"RemoveParticipant_Btn\"]:hover {\n"
"    background-color: #FFCDD2;\n"
"}\n"
"\n"
"/* --- Listas --- */\n"
"QListWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #CED4DA;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 10pt;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: #F1F3F5; /* Resaltar item al pasar el ratón */\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: #E0EFFF; /* Resaltar item seleccionado */\n"
"    color: #2C3E50;\n"
"}\n"
"   "))
        self.BackButton_Exceptions.setText(_translate("Form", "<"))
        self.TitleLabel_Exceptions.setText(_translate("Form", "Resolver Excepciones"))
        self.Label_TableParticipants.setText(_translate("Form", "Participantes en Mesa"))
        self.Label_Exceptions.setText(_translate("Form", "Participantes con Conflicto"))
        self.PrevTable_Btn.setText(_translate("Form", "Anterior Mesa"))
        self.AddParticipant_Btn.setText(_translate("Form", "Añadir"))
        self.NextTable_Btn.setText(_translate("Form", "Siguiente Mesa"))
        self.RemoveParticipant_Btn.setText(_translate("Form", "Eliminar"))
