# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\AsignarMesasAutomatico.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(667, 381)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_Titulo_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Titulo_3.setObjectName("horizontalLayout_Titulo_3")
        self.btnAtras_mesaautomatico = QtWidgets.QToolButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnAtras_mesaautomatico.setFont(font)
        self.btnAtras_mesaautomatico.setAutoRaise(True)
        self.btnAtras_mesaautomatico.setObjectName("btnAtras_mesaautomatico")
        self.horizontalLayout_Titulo_3.addWidget(self.btnAtras_mesaautomatico)
        self.labelTitulo_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo_3.setFont(font)
        self.labelTitulo_3.setObjectName("labelTitulo_3")
        self.horizontalLayout_Titulo_3.addWidget(self.labelTitulo_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Titulo_3.addItem(spacerItem)
        self.horizontalLayout_Titulo_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_Titulo_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbl_mesaparticipantes = QtWidgets.QTableWidget(Form)
        self.tbl_mesaparticipantes.setRowCount(0)
        self.tbl_mesaparticipantes.setColumnCount(2)
        self.tbl_mesaparticipantes.setObjectName("tbl_mesaparticipantes")
        item = QtWidgets.QTableWidgetItem()
        self.tbl_mesaparticipantes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_mesaparticipantes.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.tbl_mesaparticipantes)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_verExcepciones = QtWidgets.QPushButton(Form)
        self.btn_verExcepciones.setObjectName("btn_verExcepciones")
        self.verticalLayout.addWidget(self.btn_verExcepciones)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnAtras_mesaautomatico.setText(_translate("Form", "<"))
        self.labelTitulo_3.setText(_translate("Form", "Asignar Mesas Automatico"))
        item = self.tbl_mesaparticipantes.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mesa"))
        item = self.tbl_mesaparticipantes.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Participantes"))
        self.btn_verExcepciones.setText(_translate("Form", "Ver Excepciones"))
