# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\CrearEvento2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoParticipantes(object):
    def setupUi(self, DialogoParticipantes):
        DialogoParticipantes.setObjectName("DialogoParticipantes")
        DialogoParticipantes.resize(945, 677)
        self.verticalLayout_Main = QtWidgets.QVBoxLayout(DialogoParticipantes)
        self.verticalLayout_Main.setObjectName("verticalLayout_Main")
        self.horizontalLayout_Titulo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Titulo.setObjectName("horizontalLayout_Titulo")
        self.BackButton_Participants = QtWidgets.QToolButton(DialogoParticipantes)
        self.BackButton_Participants.setAutoRaise(True)
        self.BackButton_Participants.setObjectName("BackButton_Participants")
        self.horizontalLayout_Titulo.addWidget(self.BackButton_Participants)
        self.TitleLabel_Participants = QtWidgets.QLabel(DialogoParticipantes)
        self.TitleLabel_Participants.setObjectName("TitleLabel_Participants")
        self.horizontalLayout_Titulo.addWidget(self.TitleLabel_Participants)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Titulo.addItem(spacerItem)
        self.horizontalLayout_Titulo.setStretch(2, 1)
        self.verticalLayout_Main.addLayout(self.horizontalLayout_Titulo)
        self.Input_ParticipantName = QtWidgets.QLineEdit(DialogoParticipantes)
        self.Input_ParticipantName.setObjectName("Input_ParticipantName")
        self.verticalLayout_Main.addWidget(self.Input_ParticipantName)
        self.horizontalLayout_Listas = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Listas.setObjectName("horizontalLayout_Listas")
        self.verticalLayout_Invitados = QtWidgets.QVBoxLayout()
        self.verticalLayout_Invitados.setObjectName("verticalLayout_Invitados")
        self.Label_AllGuests = QtWidgets.QLabel(DialogoParticipantes)
        self.Label_AllGuests.setObjectName("Label_AllGuests")
        self.verticalLayout_Invitados.addWidget(self.Label_AllGuests)
        self.List_AllGuests = QtWidgets.QListWidget(DialogoParticipantes)
        self.List_AllGuests.setObjectName("List_AllGuests")
        self.verticalLayout_Invitados.addWidget(self.List_AllGuests)
        self.horizontalLayout_Listas.addLayout(self.verticalLayout_Invitados)
        self.verticalLayout_BotonesVX = QtWidgets.QVBoxLayout()
        self.verticalLayout_BotonesVX.setObjectName("verticalLayout_BotonesVX")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_BotonesVX.addItem(spacerItem1)
        self.MoveToPreference_Btn = QtWidgets.QPushButton(DialogoParticipantes)
        self.MoveToPreference_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.MoveToPreference_Btn.setMaximumSize(QtCore.QSize(40, 40))
        self.MoveToPreference_Btn.setObjectName("MoveToPreference_Btn")
        self.verticalLayout_BotonesVX.addWidget(self.MoveToPreference_Btn)
        self.MoveToAvoid_Btn = QtWidgets.QPushButton(DialogoParticipantes)
        self.MoveToAvoid_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.MoveToAvoid_Btn.setMaximumSize(QtCore.QSize(40, 40))
        self.MoveToAvoid_Btn.setObjectName("MoveToAvoid_Btn")
        self.verticalLayout_BotonesVX.addWidget(self.MoveToAvoid_Btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_BotonesVX.addItem(spacerItem2)
        self.horizontalLayout_Listas.addLayout(self.verticalLayout_BotonesVX)
        self.verticalLayout_Preferencia = QtWidgets.QVBoxLayout()
        self.verticalLayout_Preferencia.setObjectName("verticalLayout_Preferencia")
        self.Label_Preference = QtWidgets.QLabel(DialogoParticipantes)
        self.Label_Preference.setObjectName("Label_Preference")
        self.verticalLayout_Preferencia.addWidget(self.Label_Preference)
        self.List_Preference = QtWidgets.QListWidget(DialogoParticipantes)
        self.List_Preference.setObjectName("List_Preference")
        self.verticalLayout_Preferencia.addWidget(self.List_Preference)
        self.horizontalLayout_Listas.addLayout(self.verticalLayout_Preferencia)
        self.verticalLayout_Eliminar = QtWidgets.QVBoxLayout()
        self.verticalLayout_Eliminar.setObjectName("verticalLayout_Eliminar")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_Eliminar.addItem(spacerItem3)
        self.RemoveFromList_Btn = QtWidgets.QPushButton(DialogoParticipantes)
        self.RemoveFromList_Btn.setObjectName("RemoveFromList_Btn")
        self.verticalLayout_Eliminar.addWidget(self.RemoveFromList_Btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_Eliminar.addItem(spacerItem4)
        self.horizontalLayout_Listas.addLayout(self.verticalLayout_Eliminar)
        self.verticalLayout_NoAcepta = QtWidgets.QVBoxLayout()
        self.verticalLayout_NoAcepta.setObjectName("verticalLayout_NoAcepta")
        self.Label_Avoid = QtWidgets.QLabel(DialogoParticipantes)
        self.Label_Avoid.setObjectName("Label_Avoid")
        self.verticalLayout_NoAcepta.addWidget(self.Label_Avoid)
        self.List_Avoid = QtWidgets.QListWidget(DialogoParticipantes)
        self.List_Avoid.setObjectName("List_Avoid")
        self.verticalLayout_NoAcepta.addWidget(self.List_Avoid)
        self.horizontalLayout_Listas.addLayout(self.verticalLayout_NoAcepta)
        self.horizontalLayout_Listas.setStretch(0, 2)
        self.horizontalLayout_Listas.setStretch(2, 2)
        self.horizontalLayout_Listas.setStretch(4, 2)
        self.verticalLayout_Main.addLayout(self.horizontalLayout_Listas)
        self.horizontalLayout_BotonesFooter = QtWidgets.QHBoxLayout()
        self.horizontalLayout_BotonesFooter.setObjectName("horizontalLayout_BotonesFooter")
        self.Finish_Btn = QtWidgets.QPushButton(DialogoParticipantes)
        self.Finish_Btn.setMinimumSize(QtCore.QSize(0, 45))
        self.Finish_Btn.setObjectName("Finish_Btn")
        self.horizontalLayout_BotonesFooter.addWidget(self.Finish_Btn)
        self.Add_Btn = QtWidgets.QPushButton(DialogoParticipantes)
        self.Add_Btn.setMinimumSize(QtCore.QSize(0, 45))
        self.Add_Btn.setObjectName("Add_Btn")
        self.horizontalLayout_BotonesFooter.addWidget(self.Add_Btn)
        self.verticalLayout_Main.addLayout(self.horizontalLayout_BotonesFooter)
        self.verticalLayout_Main.setStretch(2, 1)

        self.retranslateUi(DialogoParticipantes)
        QtCore.QMetaObject.connectSlotsByName(DialogoParticipantes)

    def retranslateUi(self, DialogoParticipantes):
        _translate = QtCore.QCoreApplication.translate
        DialogoParticipantes.setWindowTitle(_translate("DialogoParticipantes", "Gestionar Participante"))
        DialogoParticipantes.setStyleSheet(_translate("DialogoParticipantes", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* --- Título Principal --- */\n"
"QLabel[objectName=\"TitleLabel_Participants\"] {\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    padding-bottom: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* --- Etiquetas de listas --- */\n"
"QLabel {\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* --- Botón de Atrás --- */\n"
"QToolButton {\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #555555;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding-right: 10px;\n"
"}\n"
"QToolButton:hover {\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* --- Botones Principales (Añadir/Finalizar) --- */\n"
"QPushButton {\n"
"    background-color: #E0EFFF; /* Azul pastel */\n"
"    color: #2C3E50;\n"
"    font-size: 14pt; /* Letra grande como en el original */\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px 18px;\n"
"    min-height: 28px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #C6DFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B0D0FF;\n"
"}\n"
"\n"
"/* --- Botón Mover a Preferencia (V) --- */\n"
"QPushButton[objectName=\"MoveToPreference_Btn\"] {\n"
"    background-color: #E8F5E9; /* Verde pastel */\n"
"    color: #388E3C; /* Verde oscuro */\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton[objectName=\"MoveToPreference_Btn\"]:hover {\n"
"    background-color: #C8E6C9;\n"
"}\n"
"\n"
"/* --- Botón Mover a No Acepta (X) --- */\n"
"QPushButton[objectName=\"MoveToAvoid_Btn\"] {\n"
"    background-color: #FFEBEE; /* Rojo pastel */\n"
"    color: #D32F2F; /* Rojo oscuro */\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton[objectName=\"MoveToAvoid_Btn\"]:hover {\n"
"    background-color: #FFCDD2;\n"
"}\n"
"\n"
"/* --- Botón Eliminar de lista --- */\n"
"QPushButton[objectName=\"RemoveFromList_Btn\"] {\n"
"    background-color: #F1F3F5; /* Gris claro */\n"
"    color: #555; /* Gris oscuro */\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton[objectName=\"RemoveFromList_Btn\"]:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"\n"
"/* --- Campo de Texto (Nombre) --- */\n"
"QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #CED4DA; /* Borde gris claro */\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    font-size: 11pt; /* Letra 11pt como en el original */\n"
"    min-height: 20px; /* Ajuste para el min-height original */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #80bdff; /* Borde azul al seleccionar */\n"
"}\n"
"\n"
"/* --- Listas --- */\n"
"QListWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #CED4DA;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 10pt;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: #F1F3F5; /* Resaltar item al pasar el ratón */\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: #E0EFFF; /* Resaltar item seleccionado */\n"
"    color: #2C3E50;\n"
"}\n"
"   "))
        self.BackButton_Participants.setText(_translate("DialogoParticipantes", "<"))
        self.TitleLabel_Participants.setText(_translate("DialogoParticipantes", "Gestionar Participante"))
        self.Input_ParticipantName.setPlaceholderText(_translate("DialogoParticipantes", "Nombre del participante"))
        self.Label_AllGuests.setText(_translate("DialogoParticipantes", "Todos los Invitados"))
        self.MoveToPreference_Btn.setText(_translate("DialogoParticipantes", "V"))
        self.MoveToAvoid_Btn.setText(_translate("DialogoParticipantes", "X"))
        self.Label_Preference.setText(_translate("DialogoParticipantes", "Preferencia (Sentar con)"))
        self.RemoveFromList_Btn.setText(_translate("DialogoParticipantes", "Eliminar"))
        self.Label_Avoid.setText(_translate("DialogoParticipantes", "No acepta (Evitar)"))
        self.Finish_Btn.setText(_translate("DialogoParticipantes", "Finalizar"))
        self.Add_Btn.setText(_translate("DialogoParticipantes", "Añadir"))
