# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\CrudEvento.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(904, 617)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLabel_Dashboard = QtWidgets.QLabel(MainWindow)
        self.TitleLabel_Dashboard.setObjectName("TitleLabel_Dashboard")
        self.horizontalLayout.addWidget(self.TitleLabel_Dashboard)
        self.OpenCSVPath_Btn = QtWidgets.QPushButton(MainWindow)
        self.OpenCSVPath_Btn.setObjectName("OpenCSVPath_Btn")
        self.horizontalLayout.addWidget(self.OpenCSVPath_Btn)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EventList_Table = QtWidgets.QTableWidget(MainWindow)
        self.EventList_Table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.EventList_Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.EventList_Table.setObjectName("EventList_Table")
        self.EventList_Table.setColumnCount(4)
        self.EventList_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.EventList_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventList_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventList_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EventList_Table.setHorizontalHeaderItem(3, item)
        self.EventList_Table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.EventList_Table)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_Botones = QtWidgets.QVBoxLayout()
        self.verticalLayout_Botones.setObjectName("verticalLayout_Botones")
        self.horizontalLayout_Botones1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Botones1.setObjectName("horizontalLayout_Botones1")
        self.AssignTables_Btn = QtWidgets.QPushButton(MainWindow)
        self.AssignTables_Btn.setObjectName("AssignTables_Btn")
        self.horizontalLayout_Botones1.addWidget(self.AssignTables_Btn)
        self.CreateEvent_Btn = QtWidgets.QPushButton(MainWindow)
        self.CreateEvent_Btn.setObjectName("CreateEvent_Btn")
        self.horizontalLayout_Botones1.addWidget(self.CreateEvent_Btn)
        self.UpdateEvent_Btn = QtWidgets.QPushButton(MainWindow)
        self.UpdateEvent_Btn.setObjectName("UpdateEvent_Btn")
        self.horizontalLayout_Botones1.addWidget(self.UpdateEvent_Btn)
        self.verticalLayout_Botones.addLayout(self.horizontalLayout_Botones1)
        self.horizontalLayout_Botones2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Botones2.setObjectName("horizontalLayout_Botones2")
        self.DeleteEvent_Btn = QtWidgets.QPushButton(MainWindow)
        self.DeleteEvent_Btn.setObjectName("DeleteEvent_Btn")
        self.horizontalLayout_Botones2.addWidget(self.DeleteEvent_Btn)
        self.GenerateCSV_Btn = QtWidgets.QPushButton(MainWindow)
        self.GenerateCSV_Btn.setObjectName("GenerateCSV_Btn")
        self.horizontalLayout_Botones2.addWidget(self.GenerateCSV_Btn)
        self.verticalLayout_Botones.addLayout(self.horizontalLayout_Botones2)
        self.verticalLayout.addLayout(self.verticalLayout_Botones)
        self.verticalLayout.setStretch(1, 10)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestor de Eventos"))
        MainWindow.setStyleSheet(_translate("MainWindow", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333; /* Texto oscuro principal */\n"
"}\n"
"\n"
"/* --- Títulos --- */\n"
"QLabel[objectName^=\"TitleLabel\"] {\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    padding-bottom: 10px;\n"
"    background-color: transparent; /* Títulos sin fondo */\n"
"}\n"
"\n"
"/* --- Botones Principales --- */\n"
"QPushButton {\n"
"    background-color: #E0EFFF; /* Azul pastel */\n"
"    color: #2C3E50;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px 18px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C6DFFF; /* Un poco más oscuro al pasar el ratón */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B0D0FF; /* Al presionar */\n"
"}\n"
"\n"
"/* --- Botones de \"Peligro\" (Borrar) --- */\n"
"QPushButton[objectName=\"DeleteEvent_Btn\"] { /* Específico para tu botón */\n"
"    background-color: #FFEBEE; /* Rosa pastel */\n"
"    color: #D32F2F; /* Rojo oscuro */\n"
"}\n"
"\n"
"QPushButton[objectName=\"DeleteEvent_Btn\"]:hover {\n"
"    background-color: #FFCDD2;\n"
"}\n"
"\n"
"/* --- Tablas --- */\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E0E0E0;\n"
"    gridline-color: #E0E0E0; /* Color de la cuadrícula */\n"
"    border-radius: 8px; /* ESQUINAS REDONDEADAS */\n"
"}\n"
"\n"
"/* --- Cabeceras de Tablas --- */\n"
"QHeaderView::section {\n"
"    background-color: #F1F3F5; /* Un gris muy claro para cabeceras */\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"}\n"
"   "))
        self.TitleLabel_Dashboard.setText(_translate("MainWindow", "Gestor de Eventos"))
        self.OpenCSVPath_Btn.setText(_translate("MainWindow", "Abrir Ruta de CSV"))
        item = self.EventList_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.EventList_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.EventList_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ubicacion"))
        item = self.EventList_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Organizador"))
        self.AssignTables_Btn.setText(_translate("MainWindow", "Asignar mesas"))
        self.CreateEvent_Btn.setText(_translate("MainWindow", "Crear evento"))
        self.UpdateEvent_Btn.setText(_translate("MainWindow", "Actualizar evento"))
        self.DeleteEvent_Btn.setText(_translate("MainWindow", "Borrar evento"))
        self.GenerateCSV_Btn.setText(_translate("MainWindow", "Generar CSV"))
