# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\EditarEvento2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(882, 652)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BackButton_UpdateEvent = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackButton_UpdateEvent.sizePolicy().hasHeightForWidth())
        self.BackButton_UpdateEvent.setSizePolicy(sizePolicy)
        self.BackButton_UpdateEvent.setObjectName("BackButton_UpdateEvent")
        self.horizontalLayout_3.addWidget(self.BackButton_UpdateEvent)
        self.Title_TextEdit = QtWidgets.QTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title_TextEdit.sizePolicy().hasHeightForWidth())
        self.Title_TextEdit.setSizePolicy(sizePolicy)
        self.Title_TextEdit.setReadOnly(True)
        self.Title_TextEdit.setObjectName("Title_TextEdit")
        self.horizontalLayout_3.addWidget(self.Title_TextEdit)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.List_Participants_Update = QtWidgets.QListView(Form)
        self.List_Participants_Update.setObjectName("List_Participants_Update")
        self.horizontalLayout_2.addWidget(self.List_Participants_Update)
        self.AddParticipant_Btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddParticipant_Btn.sizePolicy().hasHeightForWidth())
        self.AddParticipant_Btn.setSizePolicy(sizePolicy)
        self.AddParticipant_Btn.setObjectName("AddParticipant_Btn")
        self.horizontalLayout_2.addWidget(self.AddParticipant_Btn)
        self.horizontalLayout_2.setStretch(0, 12)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DeleteParticipant_Btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteParticipant_Btn.sizePolicy().hasHeightForWidth())
        self.DeleteParticipant_Btn.setSizePolicy(sizePolicy)
        self.DeleteParticipant_Btn.setObjectName("DeleteParticipant_Btn")
        self.horizontalLayout.addWidget(self.DeleteParticipant_Btn)
        self.EditParticipant_Btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditParticipant_Btn.sizePolicy().hasHeightForWidth())
        self.EditParticipant_Btn.setSizePolicy(sizePolicy)
        self.EditParticipant_Btn.setObjectName("EditParticipant_Btn")
        self.horizontalLayout.addWidget(self.EditParticipant_Btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 10)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Actualizar Evento"))
        Form.setStyleSheet(_translate("Form", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* --- Título (como QTextEdit) --- */\n"
"QTextEdit[objectName=\"Title_TextEdit\"] {\n"
"    font-size: 20pt; /* Coincide con el original */\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* --- Botones Principales (Añadir, Editar) --- */\n"
"QPushButton {\n"
"    background-color: #E0EFFF; /* Azul pastel */\n"
"    color: #2C3E50;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px 18px;\n"
"    min-height: 28px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #C6DFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B0D0FF;\n"
"}\n"
"\n"
"/* --- Botón de Atrás (Estilo especial) --- */\n"
"QPushButton[objectName=\"BackButton_UpdateEvent\"] {\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #555555;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    min-height: 0;\n"
"}\n"
"QPushButton[objectName=\"BackButton_UpdateEvent\"]:hover {\n"
"    color: #000000;\n"
"    background-color: #F0F0F0; /* Hover leve */\n"
"}\n"
"\n"
"/* --- Botón de \"Peligro\" (Borrar) --- */\n"
"QPushButton[objectName=\"DeleteParticipant_Btn\"] {\n"
"    background-color: #FFEBEE; /* Rosa pastel */\n"
"    color: #D32F2F; /* Rojo oscuro */\n"
"    font-size: 11pt; /* Fuente original */\n"
"}\n"
"QPushButton[objectName=\"DeleteParticipant_Btn\"]:hover {\n"
"    background-color: #FFCDD2;\n"
"}\n"
"\n"
"/* --- Listas (QListView) --- */\n"
"QListView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #CED4DA;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 10pt;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: #F1F3F5; /* Resaltar item al pasar el ratón */\n"
"}\n"
"QListView::item:selected {\n"
"    background-color: #E0EFFF; /* Resaltar item seleccionado */\n"
"    color: #2C3E50;\n"
"}\n"
"   "))
        self.BackButton_UpdateEvent.setText(_translate("Form", "<"))
        self.Title_TextEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ACTUALIZAR EVENTO</p></body></html>"))
        self.AddParticipant_Btn.setText(_translate("Form", "AÑADIR"))
        self.DeleteParticipant_Btn.setText(_translate("Form", "BORRAR"))
        self.EditParticipant_Btn.setText(_translate("Form", "EDITAR"))
