# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\EditarParticipante.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 643)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleLabel_EditParticipant = QtWidgets.QLabel(MainWindow)
        self.TitleLabel_EditParticipant.setObjectName("TitleLabel_EditParticipant")
        self.verticalLayout.addWidget(self.TitleLabel_EditParticipant)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Label_AllGuests = QtWidgets.QLabel(MainWindow)
        self.Label_AllGuests.setObjectName("Label_AllGuests")
        self.verticalLayout_3.addWidget(self.Label_AllGuests)
        self.Table_AllGuests = QtWidgets.QTableView(MainWindow)
        self.Table_AllGuests.setObjectName("Table_AllGuests")
        self.verticalLayout_3.addWidget(self.Table_AllGuests)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.MoveToPreference_Btn = QtWidgets.QPushButton(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.MoveToPreference_Btn.setFont(font)
        self.MoveToPreference_Btn.setObjectName("MoveToPreference_Btn")
        self.verticalLayout_8.addWidget(self.MoveToPreference_Btn)
        self.MoveToAvoid_Btn = QtWidgets.QPushButton(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.MoveToAvoid_Btn.setFont(font)
        self.MoveToAvoid_Btn.setObjectName("MoveToAvoid_Btn")
        self.verticalLayout_8.addWidget(self.MoveToAvoid_Btn)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Label_Preference = QtWidgets.QLabel(MainWindow)
        self.Label_Preference.setObjectName("Label_Preference")
        self.verticalLayout_7.addWidget(self.Label_Preference)
        self.Table_Preference = QtWidgets.QTableView(MainWindow)
        self.Table_Preference.setObjectName("Table_Preference")
        self.verticalLayout_7.addWidget(self.Table_Preference)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Label_Avoid = QtWidgets.QLabel(MainWindow)
        self.Label_Avoid.setObjectName("Label_Avoid")
        self.verticalLayout_9.addWidget(self.Label_Avoid)
        self.Table_Avoid = QtWidgets.QTableView(MainWindow)
        self.Table_Avoid.setObjectName("Table_Avoid")
        self.verticalLayout_9.addWidget(self.Table_Avoid)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.DeleteParticipant_Btn = QtWidgets.QPushButton(MainWindow)
        self.DeleteParticipant_Btn.setObjectName("DeleteParticipant_Btn")
        self.verticalLayout.addWidget(self.DeleteParticipant_Btn)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EDITAR PARTICIPANTE"))
        MainWindow.setStyleSheet(_translate("MainWindow", "\n"
"/* --- Estilo General --- */\n"
"QWidget {\n"
"    font-family: \'Segoe UI\', \'Arial\', \'sans-serif\';\n"
"    background-color: #F8F9FA; /* Un blanco roto muy suave */\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* --- Título Principal --- */\n"
"QLabel[objectName=\"TitleLabel_EditParticipant\"] {\n"
"    font-size: 24pt; /* Unificado y minimalista */\n"
"    font-weight: bold;\n"
"    color: #2C3E50; /* Un azul oscuro */\n"
"    padding-bottom: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* --- Etiquetas de listas (Invitados, Preferencia...) --- */\n"
"QLabel[objectName^=\"Label_\"] {\n"
"    font-size: 14pt; /* Unificado y minimalista */\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* --- Botones Generales (para que no afecte a los emoji) --- */\n"
"QPushButton {\n"
"    border-radius: 8px; /* ¡ESQUINAS REDONDEADAS! */\n"
"    padding: 12px;\n"
"}\n"
"\n"
"/* --- Botón Mover a Preferencia (✅) --- */\n"
"QPushButton[objectName=\"MoveToPreference_Btn\"] {\n"
"    background-color: #E8F5E9; /* Verde pastel */\n"
"    color: #388E3C; /* Verde oscuro */\n"
"    border: none;\n"
"}\n"
"QPushButton[objectName=\"MoveToPreference_Btn\"]:hover {\n"
"    background-color: #C8E6C9;\n"
"}\n"
"\n"
"/* --- Botón Mover a No Acepta (🚫) --- */\n"
"QPushButton[objectName=\"MoveToAvoid_Btn\"] {\n"
"    background-color: #FFEBEE; /* Rojo pastel */\n"
"    color: #D32F2F; /* Rojo oscuro */\n"
"    border: none;\n"
"}\n"
"QPushButton[objectName=\"MoveToAvoid_Btn\"]:hover {\n"
"    background-color: #FFCDD2;\n"
"}\n"
"\n"
"/* --- Botón de \"Peligro\" (Eliminar) --- */\n"
"QPushButton[objectName=\"DeleteParticipant_Btn\"] {\n"
"    background-color: #FFEBEE; /* Rosa pastel */\n"
"    color: #D32F2F; /* Rojo oscuro */\n"
"    font-size: 14pt; /* Tamaño legible */\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    min-height: 28px;\n"
"}\n"
"QPushButton[objectName=\"DeleteParticipant_Btn\"]:hover {\n"
"    background-color: #FFCDD2;\n"
"}\n"
"\n"
"/* --- Tablas (QTableView) --- */\n"
"QTableView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E0E0E0;\n"
"    gridline-color: #E0E0E0; /* Color de la cuadrícula */\n"
"    border-radius: 8px; /* ESQUINAS REDONDEADAS */\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"/* --- Cabeceras de Tablas --- */\n"
"QHeaderView::section {\n"
"    background-color: #F1F3F5; /* Un gris muy claro para cabeceras */\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"}\n"
"   "))
        self.TitleLabel_EditParticipant.setText(_translate("MainWindow", "EDITAR PARTICIPANTE"))
        self.Label_AllGuests.setText(_translate("MainWindow", "INVITADOS"))
        self.MoveToPreference_Btn.setText(_translate("MainWindow", "✅"))
        self.MoveToAvoid_Btn.setText(_translate("MainWindow", "🚫"))
        self.Label_Preference.setText(_translate("MainWindow", "PREFERENCIA"))
        self.Label_Avoid.setText(_translate("MainWindow", "NO ACEPTA"))
        self.DeleteParticipant_Btn.setText(_translate("MainWindow", "ELIMINAR"))
